spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springboot?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j

  # Dubbo 服务提供者配置
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.example.springboot.service

mybatis:
  type-aliases-package: com.example.springboot.entity
  mapper-locations: classpath:mappers/*.xml

mapper:
  mappers: com.example.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    rowBoundsWithCount: false
    PageRowBounds: true
    returnPageInfo: check



logging:
  level:
    com.example.springboot.dao: debug


